const appConstants = {
  ADD_COURSE: 'ADD-COURSE-OFFERING',
  REGISTER: 'REGISTER',
  CANCEL: 'CANCEL',
  ALLOT_COURSE: 'ALLOT',
  INPUT_DATA_ERROR: 'INPUT_DATA_ERROR',
  COURSE_FULL_ERROR: 'COURSE_FULL_ERROR',
  COURSE_NOT_FOUND_ERROR: 'COURSE_NOT_FOUND',
  CANCEL_REJECTED: 'CANCEL_REJECTED',
  CANCEL_ACCEPTED: 'CANCEL_ACCEPTED',
  ALREADY_REGISTERED: 'ALREADY_REGISTERED',
  COURSE_NOT_REGISTERED: 'COURSE_NOT_REGISTERED',
  COURSE_CANCELED: 'COURSE_CANCELED',
  COURSE_ARR_LENGTH: 5,
  REGISTRATION_ARR_LENGTH: 2,
}


module.exports = appConstants;