const appConstants = {
  ADD_COURSE: 'ADD-COURSE-OFFERING',
  REGISTER: 'REGISTER',
  CANCEL: 'CANCEL',
  ALLOT_COURSE: 'ALLOT',
  INPUT_DATA_ERROR: 'INPUT_DATA_ERROR',
  COURSE_FULL_ERROR: 'COURSE_FULL_ERROR'
}

module.exports = appConstants;